### ISSUE TITLE
Four files with garbled code

### ISSUE THREAD

**Issue by davidthings** [fapplin/rp2040-pico-command-line-interpreter#2]
Hi, this looks like a great starting point for a REPL / CLI, etc.  Sadly, it doesn't compile!

`console.c`, and `user_funcs.c` both seem to have a curious problem - close to the top of the file, another perhaps newer version of the file has been pasted in.  Perhaps the intention was to `select all`, `paste`, but it looks like the operation was just the `paste`.  Both files look like this:

```
old old
old old new
new
new
new
old
old
old
```
Easy enough to untangle, but not ideal!

I'm going to try to get it to compile, but my version will be USB-based vs UART-based, so you may or may not want that pull request.

Let me know!

**Comment by fapplin** [comment]
Wow! That was from quite a while back. I forgot that was even out there. Let me know how it goes.
Frank

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Aug 29, 2024 at 7:38 PM, David ***@***.***> wrote:   


Hi, this looks like a great starting point for a REPL / CLI, etc. Sadly, it doesn't compile!

console.c, and user_funcs.c both seem to have a curious problem - close to the top of the file, another perhaps newer version of the file has been pasted in. Perhaps the intention was to select all, paste, but it looks like the operation was just the paste. Both files look like this:
old old
old old new
new
new
new
old
old
old

Easy enough to untangle, but not ideal!

I'm going to try to get it to compile, but my version will be USB-based vs UART-based, so you may or may not want that pull request.

Let me know!

**Comment by davidthings** [comment]
PR added.  Lemme know if you need anything changed.
